# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(name: "tyler", email: "tyler@email.com", password: "password")
# User.create(name: "test", email: "test@email.com", password: "password")

# Team.create(name: "Chicago Cubs")
# Team.create(name: "Chicago Bulls")
# Team.create(name: "Aston Villa")
# Team.create(name: "New York Yankees")

# Sport.create(name: "Baseball")
# Sport.create(name: "Basketball")
# Sport.create(name: "Football")
# Sport.create(name: "Soccer")

# Team.create(name: "Arizona Diamondbacks", sport_id: 1)
# Team.create(name: "Atlanta Braves", sport_id: 1)
# Team.create(name: "Baltimore Orioles", sport_id: 1)
# Team.create(name: "Boston Red Sox", sport_id: 1)
# Team.create(name: "Chicago White Sox", sport_id: 1)
# Team.create(name: "Cincinnati Reds", sport_id: 1)
# Team.create(name: "Cleveland Indians", sport_id: 1)
# Team.create(name: "Colorado Rockies", sport_id: 1)
# Team.create(name: "Detroit Tigers", sport_id: 1)
# Team.create(name: "Houston Astros", sport_id: 1)
# Team.create(name: "Kansas City Royals", sport_id: 1)
# Team.create(name: "Los Angeles Angels", sport_id: 1)
# Team.create(name: "Los Angeles Dodgers", sport_id: 1)
# Team.create(name: "Miami Marlins", sport_id: 1)
# Team.create(name: "Milwaukee Brewers", sport_id: 1)
# Team.create(name: "Minnesota Twins", sport_id: 1)
# Team.create(name: "New York Mets", sport_id: 1)
# Team.create(name: "Oakland Athletics", sport_id: 1)
# Team.create(name: "Philadelphia Phillies", sport_id: 1)
# Team.create(name: "Pittsburgh Pirates", sport_id: 1)
# Team.create(name: "San Diego Padres", sport_id: 1)
# Team.create(name: "San Francisco Giants", sport_id: 1)
# Team.create(name: "Seattle Mariners", sport_id: 1)
# Team.create(name: "St. Louis Cardinals", sport_id: 1)
# Team.create(name: "Tampa Bay Rays", sport_id: 1)
# Team.create(name: "Texas Rangers", sport_id: 1)
# Team.create(name: "Toronto Blue Jays", sport_id: 1)
# Team.create(name: "Washington Nationals", sport_id: 1)

# Team.create(name: "Atlanta Hawks", sport_id: 2)
# Team.create(name: "Boston Celtics", sport_id: 2)
# Team.create(name: "Brooklyn Nets", sport_id: 2)
# Team.create(name: "Charlotte Hornets", sport_id: 2)
# Team.create(name: "Cleveland Cavaliers", sport_id: 2)
# Team.create(name: "Dallas Mavericks", sport_id: 2)
# Team.create(name: "Denver Nuggets", sport_id: 2)
# Team.create(name: "Detroit Pistons", sport_id: 2)
# Team.create(name: "Golden State Warriors", sport_id: 2)
# Team.create(name: "Houston Rockets", sport_id: 2)
# Team.create(name: "Indiana Pacers", sport_id: 2)
# Team.create(name: "Los Angeles Clippers", sport_id: 2)
# Team.create(name: "Los Angeles Lakers", sport_id: 2)
# Team.create(name: "Memphis Grizzlies", sport_id: 2)
# Team.create(name: "Miami Heat", sport_id: 2)
# Team.create(name: "Milwaukee Bucks", sport_id: 2)
# Team.create(name: "Minnesota Timberwolves", sport_id: 2)
# Team.create(name: "New Orleans Pelicans", sport_id: 2)
# Team.create(name: "New York Knicks", sport_id: 2)
# Team.create(name: "Oklahoma City Thunder", sport_id: 2)
# Team.create(name: "Orlando Magic", sport_id: 2)
# Team.create(name: "Philadelphia 76ers", sport_id: 2)
# Team.create(name: "Phoenix Suns", sport_id: 2)
# Team.create(name: "Portland Trail Blazers", sport_id: 2)
# Team.create(name: "Sacramento Kings", sport_id: 2)
# Team.create(name: "San Antonio Spurs", sport_id: 2)
# Team.create(name: "Toronto Raptors", sport_id: 2)
# Team.create(name: "Utah Jazz", sport_id: 2)
# Team.create(name: "Washington Wizards", sport_id: 2)

# Team.create(name: "Arizona Cardinals", sport_id: 3)
# Team.create(name: "Atlanta Falcons", sport_id: 3)
# Team.create(name: "Baltimore Ravens", sport_id: 3)
# Team.create(name: "Buffalo Bills", sport_id: 3)
# Team.create(name: "Carolina Panthers", sport_id: 3)
# Team.create(name: "Chicago Bears", sport_id: 3)
# Team.create(name: "Cincinnati Bengals", sport_id: 3)
# Team.create(name: "Cleveland Browns", sport_id: 3)
# Team.create(name: "Dallas Cowboys", sport_id: 3)
# Team.create(name: "Denver Broncos", sport_id: 3)
# Team.create(name: "Detroit Lions", sport_id: 3)
# Team.create(name: "Green Bay Packers", sport_id: 3)
# Team.create(name: "Houston Texans", sport_id: 3)
# Team.create(name: "Indianapolis Colts", sport_id: 3)
# Team.create(name: "Jacksonville Jaguars", sport_id: 3)
# Team.create(name: "Kansas City Chiefs", sport_id: 3)
# Team.create(name: "Los Angeles Chargers", sport_id: 3)
# Team.create(name: "Los Angeles Rams", sport_id: 3)
# Team.create(name: "Miami Dolphins", sport_id: 3)
# Team.create(name: "Minnesota Vikings", sport_id: 3)
# Team.create(name: "New England Patriots", sport_id: 3)
# Team.create(name: "New Orleans Saints", sport_id: 3)
# Team.create(name: "New York Giants", sport_id: 3)
# Team.create(name: "New York Jets", sport_id: 3)
# Team.create(name: "Oakland Raiders", sport_id: 3)
# Team.create(name: "Philadelphia Eagles", sport_id: 3)
# Team.create(name: "Pittsburgh Steelers", sport_id: 3)
# Team.create(name: "San Francisco 49ers", sport_id: 3)
# Team.create(name: "Seattle Seahawks", sport_id: 3)
# Team.create(name: "Tampa Bay Buccaneers", sport_id: 3)
# Team.create(name: "Tennessee Titans", sport_id: 3)
# Team.create(name: "Washington Redskins", sport_id: 3)

# Team.create(name: "Arsenal", sport_id: 4)
# Team.create(name: "AFC Bournemouth", sport_id: 4)
# Team.create(name: "Brigton and Hove Albion", sport_id: 4)
# Team.create(name: "Burnley FC", sport_id: 4)
# Team.create(name: "Chelsea ", sport_id: 4)
# Team.create(name: "Crystal Palace", sport_id: 4)
# Team.create(name: "Everton", sport_id: 4)
# Team.create(name: "Huddersfield Town", sport_id: 4)
# Team.create(name: "Leicester City", sport_id: 4)
# Team.create(name: "Liverpool", sport_id: 4)
# Team.create(name: "Manchester City", sport_id: 4)
# Team.create(name: "Manchester United", sport_id: 4)
# Team.create(name: "Newcastle United", sport_id: 4)
# Team.create(name: "Southampton FC", sport_id: 4)
# Team.create(name: "Stoke City", sport_id: 4)
# Team.create(name: "Swansea City", sport_id: 4)
# Team.create(name: "Tottenham Hotspur", sport_id: 4)
# Team.create(name: "Watford FC", sport_id: 4)
# Team.create(name: "West Bromwich Albion", sport_id: 4)
# Team.create(name: "West Ham United", sport_id: 4)







# NewsSource.create(api_name: "espn", display_name: "ESPN", team_id: "1", user_id: "1")
# NewsSource.create(api_name: "bbc-news", display_name: "BBC News", team_id: "3", user_id: "1")
# NewsSource.create(api_name: "espn", display_name: "ESPN", team_id: "2", user_id: "2")
# NewsSource.create(api_name: "chicago-sun-times", display_name: "Chicago Sun Times", team_id: "2", user_id: "1")
# NewsSource.create(api_name: "mlb", display_name: "MLB", team_id: "4", user_id: "2")

